spring.application.name=sitesChecker

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:botdb}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

bot.name=LuminousHomeBot
bot.token=${TELEGRAM_BOT_TOKEN}
telegrambots.long-polling.enabled=true

bot.url=${URL}
bot.textToFind=\u0417\u0430\u0438\u043C\u043A\u0430, \u0422\u043E\u043F\u043E\u043B\u0438\u043D\u0430\u044F
bot.x=52.435746
bot.y=104.388898
bot.r=0.003

bot.myChatId=358906883
bot.husbandsChatId=428123860

bot.chatIds=358906883,428123860

bot.scheduler.interval = 3600000