spring.application.name=sitesChecker

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:botdb}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

bot.name=AvocadoForMashaBot
bot.token=${TELEGRAM_BOT_TOKEN}

bot.url=${URL}
bot.textToFind=\u0411\u0430\u043A\u043B\u0430\u0448\u0438, \u0443\u043B \u042E\u0431\u0438\u043B\u0435\u0439\u043D\u0430\u044F,
bot.x=52.435746
bot.y=104.388898
bot.r=0.003

bot.myChatId=358906883
bot.husbandsChatId=428123860

bot.chatIds=358906883,428123860

bot.scheduler.interval = 3600000