spring.application.name=sitesChecker

bot.name=AvocadoForMashaBot
bot.token=${TELEGRAM_BOT_TOKEN}

bot.url=${URL}
bot.textToFind=??????, ?????????

bot.myChatId=358906883
bot.husbandsChatId=428123860

bot.chatId=358906883,428123860

bot.scheduler.interval = 3600000